version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0-browsers # < an arbitrarily chosen docker image.
    steps:
      - checkout
      - run: echo "Hello World."      
workflows:
  commit:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "53 19 * * *"
