version: 2
jobs:
  build:
    docker:
      - image: alpine:3.5 # < an arbitrarily chosen docker image.
    steps:
      - run: echo "Hello World."      
workflows:
  commit:
    jobs:
      - build
  nightly:  
    triggers:
      - schedule:
          cron: "57 19 * * *"
