version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.5 # < an arbitrarily chosen docker image.
    steps:
      - run: echo "Hello World."      
workflows:
  version: 2
  workflow_1:
    triggers:
      - schedule:
          cron: "16 20 4 11 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  
