version: 2
jobs:
  build:
    docker:
      - image: alpine:3.5 # < an arbitrarily chosen docker image.
    steps:
      - run: echo "Hello World."      
workflows:
  version: 2
  workflow_1:
    triggers:
      - schedule:
          cron: "02 20 * * *"
    jobs:
      - build
  
