version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.5 # < an arbitrarily chosen docker image.
    steps:
      - run: echo "Hello World"      
workflows:
  commit_workflow:
    jobs:
      - build
  scheduled_workflow:
    triggers:
      - schedule:
          cron: "06 12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
    
    
