version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.5 # < an arbitrarily chosen docker image.
    steps:
      - run: echo "Hello World"      
workflows:
  commit_jobs:
    jobs:
      - build
  workflow_1:
    triggers:
      - schedule:
          cron: "27 11 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
