version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.5 # < an arbitrarily chosen docker image.
    steps:
      - run: echo "Hello World"      
workflows:
  workflow_1:
    triggers:
      - schedule:
          cron: "40 11 * * *"
          filters:
            branches:
              only:
                - master
    commit:
      jobs:
        - build
