version: 2.1
jobs:
  job_1:
    docker:
      - image: alpine:3.5 # < an arbitrarily chosen docker image.
    steps:
      - run: echo "In job_1"
  job_2:
    docker:
      - image: alpine:3.5 # < an arbitrarily chosen docker image.
    steps:
      - run: echo "In job_2" 
workflows:
  workflow_1:
    jobs:
      - job_1
      - job_2
    
    
