version: 2
jobs:
  job_1:
    docker:
      - image: alpine:3.5 # < an arbitrarily chosen docker image.
    steps:
      - run: echo "In job_1"
  job_2:
    docker:
      - image: alpine:3.5 # < an arbitrarily chosen docker image.
    steps:
      - run: echo "In job_2" 
workflows:
  version: 2
  scheduled_workflow:
    triggers:
      - schedule:
          cron: "24 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - job_1
      - job_2
    
    
